name: Denopendabot
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: hasundue/denopendabot@0.18.0 # @denopendabot hasundue/denopendabot
        with:
          user-token: ${{ secrets.GH_DENOPENDABOT_TOKEN }} # needed for updating workflows